image: node:10.15.3


pipelines:
  branches:
    master:
      - step:
          name: Build
          script:
            - apt-get update && apt-get install -y unzip
            - apt-get install -y openssh-client
            - ssh root@66.29.133.129  'bash -s' < execute.sh # replace the ip with your server ip address
